# Generated by Django 5.0.2 on 2024-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilSolvenezApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
