# Generated by Django 5.0.2 on 2024-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilSolvenezApp', '0002_alter_movimientos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='saldo',
            new_name='saldo_emisor',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='saldo_receptor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='descripcion',
            field=models.CharField(choices=[('PAGO MÓVIL', 'Pago móvil'), ('TRANSFERENCIAS A TERCEROS', 'Transferencias a terceros'), ('TRANSFERENCIAS A OTROS BANCOS NACIONALES', 'Transferencias a otros bancos nacionales'), ('RECARGAS', 'Recargas'), ('PAGO DE NÓMINA', 'Pago de nómina'), ('COMPRA CON TARJETA DE DÉBITO', 'Compra con tarjeta de débito')], default='TRANSFERENCIAS A TERCEROS', max_length=50),
        ),
    ]
