# Generated by Django 5.0.2 on 2024-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilSolvenezApp', '0003_rename_saldo_movimientos_saldo_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
