# Generated by Django 5.0.2 on 2024-03-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.zona')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='zonas',
            field=models.ManyToManyField(through='user.UsuarioZona', to='user.zona'),
        ),
    ]
