# Generated by Django 5.0.2 on 2024-03-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_zona_usuariozona_user_zonas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='Zona',
            new_name='zona',
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
                ('estado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.estados')),
            ],
        ),
        migrations.AddField(
            model_name='zona',
            name='municipio_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.municipios'),
            preserve_default=False,
        ),
    ]
