# Generated by Django 5.0.2 on 2024-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_estados_rename_zona_zona_zona_municipios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
