# Generated by Django 5.0.2 on 2024-03-08 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipios',
            name='estado_fk',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='municipio_fk',
        ),
        migrations.RemoveField(
            model_name='usuariozona',
            name='usuario_fk',
        ),
        migrations.RemoveField(
            model_name='usuariozona',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zonas',
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cuenta', models.CharField(max_length=20)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros')], default='corriente', max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.DeleteModel(
            name='UsuarioZona',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
